export const ErrorRVIA = {
    600: "Error en número de argumentos",
    601: "Argumentos inválidos",
    602: "NO SE PUDO ABRIR EL ARCHIVO PARA LEER EL TOKEN",
    603: "NO SE PUDO ABRIR EL ARCHIVO CHECKMARX" ,
    604: "Error en número de argumentos [getTotalFiles]",
    605: "Argumentos inválidos (getTotalFiles)",
    606: "Error: system call failed. (getTotalFiles)",
    607: "Command failed with exit status",
    608: "Command did not terminate normally.",
    609: "ERROR: El archivo de totales está vacío.",
    610: "Error: system call failed. (getTotalCloc)",
    611: "Command failed with exit status (getTotalCloc)",
    612: "Command did not terminate normally (getTotalCloc).",
    613: "ERROR: El archivo de totales está vacío (getTotalCloc).",
    614: "Error: Incorrect employee number.. (getTotalCloc)",
    615: "Error: No se pudo registrar el control del proyecto.",
    616: "Error: No se pudo registrar el lenguaje",
    617: "Error en número de argumentos [validateTBEmployeeExists]",
    618: "Argumentos inválidos [validateTBEmployeeExists]",
    619: "No se pudo abrir el archivo para leer el token.",
    620: "El token proporcionado no coincide con el token guardado.",
    621: "El token ha expirado.",
    622: "Error en número de argumentos (initEncryptDecryptRvia)",
    623: "Argumentos inválidos (initEncryptDecryptRvia)",
    624: "Tipo de archivo incorrecto (initEncryptDecryptRvia)",
    625: "Error: system call failed. [processFile]",
    626: "Error: system call failed. [processFileWithCheckmarx]",
    627: "Error: system call failed. [processFileByReinforcement]",
    628: "Error en número de argumentos [getTotalDataFromCheckmarx]",
    629: "Argumentos inválidos [getTotalDataFromCheckmarx]",
    630: "Error en número de argumentos [createOverviewDoc]",
    631: "Argumentos inválidos [createOverviewDoc]",
    632: "Error al cambiar de directorio [createOverviewDoc]",
    633: "Error al ejecutar el script. [createOverviewDoc]",
    634: "Error al comprimir el directorio [createOverviewDoc].",
    635: "Error al cambiar al directorio origen [createOverviewDoc].",
    636: "El directorio no existe o no es un directorio: [deleteDirectory]",
    637: "Error al abrir archivo [saveLatestRecordsDocumentationBito]",
    638: "En argumento númerico [createOverviewDoc]",
    639: "En argumento, no es número de empleado [createOverviewDoc]",
    640: "En argumento string [createOverviewDoc]",
    641: "En número de argumentos [compress]",
    642: "Al actualizar estatus [initprocess]",
    643: "Al ejecutar proceso IA por actualización [initProcess]",
    644: "Al comprimir proyecto por actualizacion [initProcess]",
    645: "Al ejecutar la IA con Checkmarx [initProcess]",
    646: "Al comprimir proyecto por checkmarx [initProcess]",
    647: "En argumentos al comprimir archivo [compressor]",
    648: "En argumentos al comprimir archivo [compressor]",
    649: "El comando falló con el estado de salida [createOverviewDocLocal]",
    650: "El comando no finalizó normalmente [createOverviewDocLocal]",
    651: "No se pudo abrir el archivo de log.",
    652: "Al crear documentación overview [initProcess]",
    653: "Al crear documentación overview por checkmarx [initProcess]",
    654: "El empleado no existe o no hay conexión [getTotalFiles]",
    655: "No se pudo abrir el archivo de totales [getTotal]",
    666: "El empleado no existe o no hay conexión [initProcess];",
    667: "Al registrar comentarios del proyecto [executeProcessAI]",
    668: "No se pudo procesar el archivo [executeProcessAI]",
    669: "No se pudo procesar el archivo Javascript [executeProcessAI]",
    670: "No se pudo procesar el archivo Typescript [executeProcessAI]",
    671: "No se pudo procesar el archivo Java [executeProcessAI]",
    672: "No se pudo procesar el archivo Dart [executeProcessAI]",
    673: "No se pudo procesar el archivo CPP [executeProcessAI]",
    674: "No se pudo procesar el archivo HPP [executeProcessAI]",
    675: "No se pudo procesar el archivo H [executeProcessAI]",
    676: "No se pudo procesar el archivo CS [executeProcessAI]",
    677: "No se pudo procesar el archivo PYTHON [executeProcessAI]",
    678: "No se pudo procesar el archivo Visual Basic 6 [executeProcessAI]",
    679: "No se pudo procesar el archivo Visual Basic .NET [executeProcessAI]",
    680: "Al actualizar el estatus de finalizado [executeProcessAI]",
    681: "Se encontraron errores de sintaxis en el archivo original [executeProcessAIWithCheckmarx]",
    682: "No se pudo procesar el archivo con checkmarx [executeProcessAIWithCheckmarx]",
    683: "Al registar comentarios IA con checkmarx [executeProcessAIWithCheckmarx]",
    684: "Al actualizar el estatus finalizado IA con checkmarx [executeProcessAIWithCheckmarx]",
    685: "En archivo no se convirtió con IA [processFile] Filename :",
    686: "Al validar el archivo con IA [processFileWithCheckmarx] FileNameIA",
    687: "El lenguaje AAAA no está soportado [getPromptBito]",
    688: "El archivo no se pudo convertir [validateBitoFile]",
    689: "El archivo no existe [removeCommentsBito] fileArg",
    690: "El archivo no existe [removeCommentsBito] pathFile",
    691: "Al abrir el archivo [lintPHPFile] stemLint",
    692: "En archivo [lintPHPFile] sFileName",
    693: "Al remover los archivos temporales [lintPHPFile] stemLint",
    694: "El comando falló con el estado de salida [createOverviewDoc]",
    695: "El comando no finalizó normalmente [createOverviewDoc]",
    696: "Al desinfectar la entrada:",
    697: "No se encontraron datos en el archivo Checkmarx. [getTotalDataFromCheckmarx]",
    698: "El directorio no existe [search_files_deprecated_in_directory]",
    699: "Al conectar con la base de datos [registerObsoleteFunctions]",
    700: "No se encontró el carácter '_' [initprocess]",
    701: "No se pudo abrir el archivo de totales checkmarx [initProcess]",
    702: "No se pudieron registrar los totales de Checkmarx [initProcess]",
    703: "Lenguaje no encontrado [getPromptBitoDB]",
    704: "No se pudo obtener el tipo de base de datos",
    705: "Al abrir archivo [CAnalyzeFileCppAndC::processFile]",
    706: "En la llamada al sistema [CAnalyzeFileCppAndC::processFile]",
    707: "En archivo no se convirtió con IA [CAnalyzeFileCppAndC::processFile] Filename :",
    708: "Al renombrar archivos: [renameFiles]",
    709: "No se pudo abrir el archivo [readContentFile]",
    710: "Error",
    711: "Error",
    712: "Error",
    713: "Error",
    714: "Error",
    715: "Error",
    716: "Error",
    717: "Error",
    718: "Error",
    719: "Error",
    720: "Error"
}